cmsapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'cmsapp'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^BAD/$', views.bad),
    url(r'^add/page/$', views.page_change, name='add'),
    url(r'^add/sidebarpage/$', views.page_change, {'kind': 'sidebar'}, name='add-sidebar'),
    url(r'^tag/(?P<tag>[^/]+)/$', views.IndexView.as_view(), name='index'),
    url(r'^moderate/$', views.ModerateIndexView.as_view(), name='moderate'),
    url(r'^moderate/(?P<pk>[0-9]+)/$', views.page_moderate, name='moderate'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', views.PageView.as_view(), name='page'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/edit$', views.page_change, name='change'),
    # url(r'^(?P<slug>[-a-zA-Z0-9_]+)/edit$', views.PageChangeView.as_view(), name='change'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/delete$', views.PageDeleteView.as_view(), name='delete'),
]

cmsproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/rosetta/', include('rosetta.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('cmsapp.urls')),
]

cmsapp/models.py
from binascii import hexlify

from django.core.exceptions import ValidationError
from os import urandom

from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class Tag(models.Model):
    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')

    name = models.CharField(verbose_name=_('Name'), max_length=200)
    page = models.ForeignKey("Page", verbose_name=_('Page'),
                             on_delete=models.CASCADE, related_name='tags', related_query_name='tag')

    def __repr__(self):
        return "<Tag page={0.page.pk}/{0.page.slug!r} name={0.name!r:.5}>".format(self)


def get_random_slug():
    return hexlify(urandom(8))


# class PageManager(models.Manager):
#     def get_queryset(self):
#         return super(PageManager, self).get_queryset().filter(is_draft=False, is_deleted=False)

class Page(models.Model):
    class Meta:
        verbose_name = _('Page')
        verbose_name_plural = _('Pages')
        permissions = (
            ('publish', 'Can publish changes'),
        )
        unique_together = 'slug', 'is_draft'

    slug = models.SlugField(verbose_name=_('Slug'), max_length=200, blank=False, default=get_random_slug)
    title = models.CharField(verbose_name=_('Title'), max_length=200)
    content = models.TextField(verbose_name=_('Content'))

    is_deleted = models.BooleanField(default=False)
    is_draft = models.BooleanField(default=False)
    revision_of = models.OneToOneField("self", null=True, related_name="pending_draft", on_delete=models.CASCADE, blank=True)

    def get_absolute_url(self):
        return reverse('cmsapp:page', kwargs={'slug': self.slug})

    def validate_unique(self, exclude=None):
        if self.is_draft:
            cls = type(self)
            qs = cls.objects.filter(slug=self.slug, is_draft=False)
            if self.pk:
                qs = qs.exclude(pk=self.pk)
            if self.revision_of:
                qs = qs.exclude(pk=self.revision_of_id)
            if qs.exists():
                raise ValidationError(self.unique_error_message(cls, ['slug']))
        super(Page, self).validate_unique(exclude)

    # @property
    # def moderation_id(self):
    #     return getattr(self, 'page_ptr_id', self.pk)

    def __repr__(self):  # https://pyformat.info/
        return "<{0.__class__.__name__} #{0.pk} draft={1} " \
               "slug={0.slug!r} title={0.title!r} content={0.content!r:.5}>".format(
            self,
            self.is_draft and self.revision_of_id
        )


class SidebarPage(Page):
    class Meta:
        verbose_name = _('SidebarPage')
        verbose_name_plural = _('SidebarPages')

    sidebar_title = models.CharField(max_length=200)


class SidebarItem(models.Model):
    sidebar_page = models.ForeignKey("SidebarPage",
                                     on_delete=models.CASCADE,
                                     related_name='sidebar_items',
                                     related_query_name='sidebar_item')
    content = models.TextField()

cmsapp/forms.py
from django import forms
from djangoformsetjs.utils import formset_media_js

from .models import Page, Tag, SidebarPage, SidebarItem


class TagField(forms.CharField):
    def clean(self, value):
        value = super(TagField, self).clean(value)

        tags = [item.strip() for item in value.split(',')]
        return [tag for tag in tags if tag]


# an altenative to having multiple classes for
# each page specialization

# def pageform_factory(kind):
#     class PageForm(forms.ModelForm):
#         class Meta:
#             if kind == 'page':
#                 model = Page
#                 fields = "slug", "title", "tags", "content"
#             elif kind == 'sidebar':
#                 model = SidebarPage
#                 fields = "slug", "title", "tags", "content", "sidebar_title"
#             else:
#                 raise RuntimeError("Unexpected page kind %r!" % kind)
#
#         tags = TagField(required=False)
#
#         def __init__(self, data=None, *, initial=None, instance=None, **kwargs):
#             if instance:
#                 initial = initial or {}
#                 initial['tags'] = ', '.join(instance.tags.values_list('name', flat=True))
#             return super(PageForm, self).__init__(data, initial=initial, instance=instance, **kwargs)
#
#         def save(self, commit=True):
#             instance = super(PageForm, self).save(commit)
#             if commit:
#                 self.instance.tags.all().delete()
#                 Tag.objects.bulk_create([
#                     Tag(name=tag, page=instance)
#                     for tag in self.cleaned_data['tags']
#                 ])
#             return instance
#
#     return PageForm

# the advantage is that we could use the
# factory directly from the view
#   Form = pageform_factory('page')
#   Form = pageform_factory('sidebar')
# however not worth the hassle for just
# two specializations

class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = "slug", "title", "tags", "content"

    tags = TagField(required=False)

    def __init__(self, data=None, *, initial=None, instance=None, **kwargs):
        if instance:
            initial = initial or {}
            initial['tags'] = ', '.join(instance.tags.values_list('name', flat=True))
        return super(PageForm, self).__init__(data, initial=initial, instance=instance, **kwargs)

    def save(self, commit=True):
        instance = super(PageForm, self).save(commit)
        if commit:
            self.instance.tags.all().delete()
            Tag.objects.bulk_create([
                Tag(name=tag, page=instance)
                for tag in self.cleaned_data['tags']
            ])
        return instance

class SidebarPageForm(PageForm):
    class Meta:
        model = SidebarPage
        fields = "slug", "title", "tags", "content", "sidebar_title"



class SidebarItemForm(forms.Form):
    class Media:
        js = formset_media_js

    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 2}))


SidebarItemFormset = forms.formset_factory(form=SidebarItemForm, extra=5)

# we can't usa the inlineformset because it
# would move the items on the draft instead
# of copying them

# SidebarItemFormset = forms.inlineformset_factory(
#     SidebarPage, SidebarItem, fk_name='sidebar_page',
#     form=SidebarItemForm,
#     fields=["content"],
#     widgets={'content': forms.Textarea(attrs={'rows': 2})},
#     extra=5
# )


class PageDeleteForm(forms.Form):
    delete = forms.BooleanField(label="Yes, I'm sure I want to delete", required=False)

    def clean(self):
        cleaned_data = super(PageDeleteForm, self).clean()
        if not cleaned_data.get('delete'):
            raise forms.ValidationError('Must confirm the delete!')
        return cleaned_data

cmsapp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.db import transaction
from django.http import HttpResponseBadRequest
from django.shortcuts import reverse, redirect, render, get_object_or_404
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.views.generic.detail import BaseDetailView, SingleObjectTemplateResponseMixin
from django.views.generic.edit import FormMixin, DeletionMixin

from .forms import PageForm, PageDeleteForm, SidebarPageForm, SidebarItemFormset
from .models import Page, Tag, SidebarPage, SidebarItem


class IndexView(ListView):
    queryset = Page.objects.filter(is_draft=False)
    paginate_by = 10
    ordering = 'pk'

    def get_context_data(self):
        return super(IndexView, self).get_context_data(
            tags=Tag.objects.filter(page__is_draft=False).values('name').distinct(),
            moderate_count=Page.objects.filter(is_draft=True).count()
            if self.request.user.has_perm('cmsapp.can_publish') else 0,
        )

    def get_queryset(self):
        qs = super(IndexView, self).get_queryset()
        if 'tag' in self.kwargs:
            return qs.filter(tag__name=self.kwargs['tag'])
        else:
            return qs


class ModerateIndexView(ListView):
    queryset = Page.objects.filter(is_draft=True)
    paginate_by = 10
    ordering = 'pk'
    template_name_suffix = '_moderate_list'


@permission_required('cmsapp.can_publish')
@transaction.atomic
def page_moderate(request, pk):
    basedraft = get_object_or_404(Page, is_draft=True, pk=pk)
    draft = getattr(basedraft, 'sidebarpage', basedraft)

    if request.method == "POST":
        action = request.POST.get('action')
        if action == 'publish':
            old_page = draft.revision_of
            if old_page:
                draft.revision_of = None
                draft.save()
                old_page.delete()
            draft.is_draft = False
            draft.save()
            messages.add_message(
                request, messages.WARNING,
                _("Draft for {title!r} was published.").format(title=draft.title))
        elif action == 'discard':
            draft.delete()
            messages.add_message(
                request, messages.WARNING,
                _("Draft for {title!r} was discarded.").format(title=draft.title))
        else:
            return HttpResponseBadRequest("Looks like someone is messing around ...")
        return redirect("cmsapp:moderate")
    return render(request, "cmsapp/page_moderate_detail.html", {
        'page': draft,
        'sidebar': getattr(basedraft, 'sidebarpage', None),
        'tags': draft.tags.all(),
    })


class PageView(DetailView):
    queryset = Page.objects.filter(is_draft=False)
    slug_url_kwarg = 'slug'  # this is by default

    def get_context_data(self, object):
        return super(PageView, self).get_context_data(
            page=object,
            sidebar=getattr(object, 'sidebarpage', None),
            tags=object.tags.all()
        )


@method_decorator(login_required, name='dispatch')
class PageDeleteView(DeletionMixin, FormMixin, SingleObjectTemplateResponseMixin, BaseDetailView):
    template_name_suffix = '_confirm_delete'
    model = Page
    form_class = PageDeleteForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.delete(request)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse('cmsapp:index')


@method_decorator(login_required, name='dispatch')
class PageAddView(CreateView):
    model = Page
    form_class = PageForm


@login_required
@transaction.atomic
def page_change(request, slug=None, kind='page'):
    if slug is None:
        instance = None
    else:
        instance = get_object_or_404(Page, slug=slug, is_draft=False)
        if getattr(instance, 'sidebarpage', None):
            kind = 'sidebar'
            instance = instance.sidebarpage
    if kind == 'page':
        Model = Page
        Form = PageForm
        Formset = None
    elif kind == 'sidebar':
        Model = SidebarPage
        Form = SidebarPageForm
        Formset = SidebarItemFormset
    else:
        raise RuntimeError("Unexpected kind %r!" % kind)

    pending_draft = getattr(instance, 'pending_draft', None)
    if pending_draft:
        return redirect("cmsapp:moderate", pk=pending_draft.pk)

    if request.method == "POST":
        draft = Model(is_draft=True, revision_of=instance)
        form = Form(request.POST, instance=draft)
        if Formset:
            # inlinemodelformset would need the „instance” argument
            formset = Formset(request.POST)  # , instance=instance)
        else:
            formset = None
        if form.is_valid() and (not formset or formset.is_valid()):
            form.save()
            if formset:
                for data in formset.cleaned_data:
                    if data:
                        SidebarItem.objects.create(sidebar_page=draft, **data)
            messages.add_message(
                request, messages.INFO,
                _("Your page {title!r} was saved and it's waiting moderation. A moderator can publish it.").format(
                    title=draft.title))
            return redirect("cmsapp:index")
    else:
        form = Form(instance=instance)
        # inlinemodelformset would need the „instance” argument
        formset = Formset and Formset(initial=instance.sidebar_items.values())  # instance=instance)

    return render(request, "cmsapp/page_form.html", {
        'form': form,
        'formset': formset,
        'title': (
            _('Editing {model}') if instance else _('Adding a {model}')
        ).format(model=Model._meta.verbose_name),
    })


@method_decorator(login_required, name='dispatch')
class PageChangeView(UpdateView):
    model = Page
    form_class = PageForm


def bad(request):
    raise Exception("Boooo %s!" % Page.objects.count())  # pragma: nocover

cmsapp/templates/cmsapp/page_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
    {% trans "Delete page?" %}
{% endblock %}

{% block body%}
    <form method="post">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <button type="submit">{% trans "Save" %}</button>
    </form>
{% endblock %}

cmsapp/templates/cmsapp/page_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{{ page.title }}{% endblock %}

{% block crumb %}
<h1><a href="{% url 'cmsapp:index' %}">{% trans "Home" %}</a> >
{{ page.title }}
<a href="{% url 'cmsapp:change' page.slug %}">{% trans "Edit" %}</a>
<a href="{% url 'cmsapp:delete' page.slug %}">{% trans "Delete" %}</a>
</h1>
{% endblock %}
{% block body%}
{% include "cmsapp/includes/tags.html" %}

{% if sidebar %}
    <div class="sidebar">
    <h2>{{ sidebar.sidebar_title }}</h2>
    <ul>
        {% for item in sidebar.sidebar_items.all %}
        <li>{{ item.content }}</li>
        {% endfor %}
    </ul>
    </div>
{% endif %}
<p>{{ page.content }}</p>
{% endblock %}

cmsapp/templates/cmsapp/page_form.html
{% extends "base.html" %}
{% load formset_tags %}
{% load i18n %}
{% block title %}
    {% if page %}
        {{ page.title }} [editing]
    {% else %}
        [adding new page]
    {% endif %}
{% endblock %}

{% block body%}
    <h1><a href="{% url 'cmsapp:index' %}">{% trans "Home" %}</a> > {{ title }}</h1>
    <form method="post">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        {% if formset %}
        <h3>Sidebar items</h3>

        {{ formset.media }}
        <blockquote id="formset" data-formset-prefix="{{ formset.prefix }}">
            {{ formset.management_form }}
            <div data-formset-body>
            {% for form in formset %}
                <div data-formset-form>
                    <table>{{ form.as_table }}</table>
                </div>
            {% endfor %}
            </div>

            <script type="form-template" data-formset-empty-form>{% escapescript %}
                <div data-formset-form>
                    <table>{{ formset.empty_form }}</table>
                </div>
            {% endescapescript %}</script>

            <input type="button" value="Add another" data-formset-add>
            <script>jQuery(function($) {
                $("#formset").formset();
            });</script>
        </blockquote>
        {% endif %}

        <button type="submit">{% trans "Save" %}</button>
    </form>
{% endblock %}

cmsapp/templates/cmsapp/page_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Pages" %}{% endblock %}

{% block crumb %}
<h1>
    {% trans "Home" %}
    |
    <a href="{% url 'cmsapp:add' %}">{% trans "Add" %}</a> (<a href="{% url 'cmsapp:add-sidebar' %}">{% trans "sidebar" %}</a>)
</h1>
{% endblock %}

{% block body %}
{% include "cmsapp/includes/tags.html" %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    {% if moderate_count %}
        <li><a href="{% url 'cmsapp:moderate' %}">
            {% blocktrans %}{{ moderate_count }} pages are awaiting moderation.{% endblocktrans %}
        </a></li>
    {% endif %}
</ul>

{% block pages %}
    <h2>{% trans "Pages" %}</h2>
    <ul>
        {% for page in object_list %}
        <li><a href="{% url 'cmsapp:page' page.slug %}">{{ page.title}}</a></li>
        {% empty %}
        {% trans "No pages yet!" %}
        {% endfor %}
    </ul>
{% endblock %}
{% if object_list %}
<p>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">previous</a> |
    {% endif %}
    {% with page_number=page_obj.number total_pages=paginator.num_pages %}
        {% blocktrans %}page {{ page_number }} of {{ total_pages }}{% endblocktrans %}
    {% endwith %}

    {% if page_obj.has_next %}
        | <a href="?page={{ page_obj.next_page_number }}">next</a>
    {% endif %}
</p>
{% endif %}
{% endblock %}

cmsapp/templates/cmsapp/page_moderate_detail.html
{% extends "cmsapp/page_detail.html" %}
{% load i18n %}
{% block title %}
    {% blocktrans with title=page.title%}
        Moderate {{ title }}
    {% endblocktrans %}
{% endblock %}

{% block crumb %}
<form method="post">{% csrf_token %}
<h1>
    <a href="{% url 'cmsapp:index' %}">{% trans "Home" %}</a>
    >
    <a href="{% url 'cmsapp:moderate' %}">{% trans "Moderation" %}</a>
    >
    {{ page.title }}
    |
    <button type="submit" name="action" value="publish">Publish</button>
    <button type="submit" name="action" value="discard">Discard</button>
</h1>
</form>
{% endblock %}

cmsapp/templates/cmsapp/page_moderate_list.html
{% extends "cmsapp/page_list.html" %}
{% load i18n %}

{% block crumb %}
<h1><a href="{% url 'cmsapp:index' %}">{% trans "Home" %}</a> > {% trans "Moderation" %}</h1>
{% endblock %}

{% block pages %}
    <h2>{% trans "Pages awaiting moderation" %}</h2>
    <ul>
        {% for page in object_list %}
        <li><a href="{% url 'cmsapp:moderate' page.pk %}">{{ page.title}}</a></li>
        {% empty %}
        {% trans "Great job! Nothing to moderate left." %}
        {% endfor %}
    </ul>
{% endblock %}